import os
x=1
while x==1:
	
      os.system('clear')
      print("#       #           #")
      print("#       #           #")
      print("#       #   #####   #   #####   # #####")
      print("#########  #     #  #  #     #  ##     #")
      print("#       #  #######  #  #######  #      #")
      print("#       #  #        #  #        #      #")
      print("#       #  #        #  #        #      #")
      print("#       #   ######  #   ######  #      #")
      os.system('clear')
      print(" #       #           #")
      print(" #       #           #")
      print(" #       #   #####   #   #####   # #####")
      print(" #########  #     #  #  #     #  ##     #")
      print(" #       #  #######  #  #######  #      #")
      print(" #       #  #        #  #        #      #")
      print(" #       #  #        #  #        #      #")
      print(" #       #   ######  #   ######  #      #")
      os.system('clear')
      print("	#       #           #")
      print("	#       #           #")
      print("	#       #   #####   #   #####   # #####")
      print("	#########  #     #  #  #     #  ##     #")
      print("	#       #  #######  #  #######  #      #")
      print("	#       #  #        #  #        #      #")
      print("	#       #  #        #  #        #      #")
      print("	#       #   ######  #   ######  #      #")
      os.system('clear')
      print(" 	 #       #           #")
      print(" 	 #       #           #")
      print(" 	 #       #   #####   #   #####   # #####")
      print("  	 #########  #     #  #  #     #  ##     #")
      print("	 #       #  #######  #  #######  #      #")
      print("	 #       #  #        #  #        #      #")
      print("	 #       #  #        #  #        #      #")
      print("	 #       #   ######  #   ######  #      #")
      os.system('clear')
      print("		#       #           #")
      print("		#       #           #")
      print("		#       #   #####   #   #####   # #####")
      print("		#########  #     #  #  #     #  ##     #")
      print("		#       #  #######  #  #######  #      #")
      print("		#       #  #        #  #        #      #")
      print("		#       #  #        #  #        #      #")
      print("		#       #   ######  #   ######  #      #")
      
    
